services:

  postgres:
    image: postgres:17
    container_name: postgres-api-biblia
    restart: unless-stopped

    environment:
      POSTGRES_DB: api_biblia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: api-biblia
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

    depends_on:
      - postgres

volumes:
  postgres_data: